### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by sharegrams** [victorqribeiro/aimAndShoot#1]
I got to generation 35 and then this lucky little punk got lucky with his spraying trajectory on spawn. Blasted me with a whole string of them.

**Comment by victorqribeiro** [comment]
I don't have a server. I only have a hosting provider. it's very cheap but very unreliable. I try as much as I can to don't use data storage on my projects. so, for now, I don't think I'll implement a persistent high score system. what I could do is keep track of your personal best and store it on the client side. but then again: that information wouldn't be trust worthy, cause the client could manipulate it.

**Comment by elimisteve** [comment]
@victorqribeiro This projects sounds awesome! A $5/month DigitalOcean server would still be pretty cheap and way more reliable than the current setup :-).  Looks like DNS isn't resolving:

```
$ ping victorribeiro.com
ping: victorribeiro.com: Temporary failure in name resolution
```

**Comment by victorqribeiro** [comment]
yeah, since I started a full job I've been thinking about renting a virtual server. I heard Amazon's is pretty good. I'll take a look at both

**Comment by elimisteve** [comment]
@victorqribeiro Yes, Amazon EC2 and DigitalOcean are both great. DO is much simpler to get started with, but EC2 will look better on your resume because it's more popular and used by many companies.

**Comment by victorqribeiro** [comment]
I'm kinda good with Linux. I just need a place where I can ssh in and install and configure what I want. I just get lost with all this service available this days. vps, elastic s3... I don't know which one is a Linux distro connected to the internet, and I never took the time to look it up.

**Comment by elimisteve** [comment]
Makes sense. I'd sign up for digitalocean.com , select $5/month server running Ubuntu 18.04, and you'll be good to go!

**Comment by victorqribeiro** [comment]
I did it. I'm now on digital ocean with the $5 linux server. Let's see how it goes...

**Comment by elimisteve** [comment]
Way to go!


On Friday, November 8, 2019, Victor Ribeiro <notifications@github.com>
wrote:
> I did it. I'm now on digital ocean with the $5 linux server. Let's see
how it goes...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/DIMHMyNoJMp1YyatcFkSv6KaSKMKiGoHLqZJOFgdermcv1gwbl3P6XB3DUleOWW1DO8SSd1VpXMPSLJpWMc8OvnGZFomPgyeOO5WWZAs5r86a0np_aq6doDw7HsP8Kb4dy46zxUO0Vy_C5qNLt_JO39cpH6ihlKzxwI2PqaNLTD3k9JCGhgj_kcod9K6NKtDgczCzBk1Pp4ZyP4xeTlsCraEV2ow7HZNfb7pjRA3jw=s0-d-e1-ft#https://github.com/notifications/beacon/AABCCU7N32LYWHRBID3PUILQSVTNFA5CNFSM4JCXPIEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDR52WQ.gif>
