### ISSUE TITLE
Space to shoot

### ISSUE THREAD

**Issue by JadedBlueEyes** [victorqribeiro/aimAndShoot#5]

**Comment by JadedBlueEyes** [comment]
?

**Comment by victorqribeiro** [comment]
is this how you normally communicate with people?

**Comment by JadedBlueEyes** [comment]
No, but there was nothing more to be said. I made a suggestion - add a control to use space to shoot. When you closed it without explanation, I looked to see if anything had changed, but there had been no commits since before I opened the issue. I responded with a question mark to indicate confusion and suggest that you should explain.
If you don't understand my communication, please ask.
If you want people to follow a set format when opening issues on your repository, tell them, preferably through [issue templates](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).
